jalur = [
    ("PMDK"),
    ("USMI"),
    ("USM2"),
    ("USM3"),
    ("USM"),
    ("USM 1"),
    ("USM 2"),
    ("USM 3"),
    ("USM 2A"),
    ("USM 2B"),
    ("USM 3A"),
    ("USM 3B"),
    ("UTBK"),
]

prodi = [
    ("S1", "Informatika"),
    ("S1", "Sistem Informasi"),
    ("S1", "Teknik Elektro"),
    ("S1", "Manajemen Rekayasa"),
    ("S1", "Teknik Bioproses"),
    ("D4", "Sarjana Terapan Teknologi Rekayasa Perangkat Lunak"),
    ("D3", "Teknologi Informasi"),
    ("D3", "Teknologi Komputer"),
]

jenis_kelamin = [
    ("Laki-Laki"),
    ("Perempuan"),
]


prodi_dict = {
    "Teknologi Informasi": {
        "code": 1,
        "jenjang": "D3",
        "minimum_semester": 4,
    },
    "Sarjana Terapan Teknologi Rekayasa Perangkat Lunak": {
        "code": 2,
        "jenjang": "D4",
        "minimum_semester": 6,
    },
    "Informatika": {
        "code": 3,
        "jenjang": "S1",
        "minimum_semester": 6,
    },
    "Sistem Informasi": {
        "code": 4,
        "jenjang": "S1",
        "minimum_semester": 6,
    },
    "Teknologi Komputer": {
        "code": 5,
        "jenjang": "D3",
        "minimum_semester": 4,
    },
    "Teknik Elektro": {
        "code": 6,
        "jenjang": "S1",
        "minimum_semester": 6,
    },
    "Manajemen Rekayasa": {
        "code": 7,
        "jenjang": "S1",
        "minimum_semester": 6,
    },
    "Teknik Bioproses": {
        "code": 8,
        "jenjang": "S1",
        "minimum_semester": 6,
    },
}

jalur_dict = {
    "PMDK": 1,
    "USMI": 2,
    "USM2": 3,
    "USM3": 4,
    "USM": 5,
    "USM 1": 6,
    "USM 2": 7,
    "USM 3": 8,
    "USM 2A": 9,
    "USM 2B": 10,
    "USM 3A": 11,
    "USM 3B": 12,
    "UTBK": 13,
}

jenis_kelamin_dict = {"Laki-Laki": 0, "Perempuan": 1}

nama_sma_dict = {
    "SMA Santa Maria Tarutung": 0,
    "SMA Negeri 1 Girsang Sipanganbolon Parapat": 1,
    "SMA Negeri 1 Girsang Sipangan Bolon": 2,
    "SMA Negeri 2 Balige": 3,
    "SMK Negeri 1 Siatasbarita ": 4,
    "SMK YAPIM BALIGE": 5,
    "SMK Negeri 1 Lumbanjulu": 6,
    "SMA Negeri 1 Pangaribuan": 7,
    "SMA Negeri 1 Balige": 8,
    "SMK Negeri 1 Siborongborong": 9,
    "SMA Negeri 1 Habinsaran": 10,
    "SMA N 1 Pintu Pohan Meranti": 11,
    "SMA Negeri 4 Kisaran": 12,
    "SMA Negeri 4 Kota Pematang Siantar": 13,
    "SMA Bintang Timur Balige": 14,
    "SMA RK Bintang Timur Pematang Siantar": 15,
    "SMA Negeri 4 Medan": 16,
    "SMA Negeri 1 Sidikalang": 17,
    "SMA Budi Murni 1 Medan": 18,
    "SMA Methodist Pematang Siantar": 19,
    "SMA Negeri 17 Medan": 20,
    "SMA Fransiskus Sibolga": 21,
    "SMA Negeri 1 Tanjung Morawa": 22,
    "SMA Cahaya Medan": 23,
    "SMA Negeri 4 Pematang Siantar ": 24,
    "SMA Negeri 5 Medan": 25,
    "SMA RK Budi Mulia Pematang Siantar": 26,
    "SMA Negeri 2 Sidikalang": 27,
    "SMA Negeri 14 Medan": 28,
    "SMA Methodist 8 Medan": 29,
    "SMA Negeri 1 Dolok Sanggul": 30,
    "SMA Negeri 4 Pematang Siantar": 31,
    "SMA Negeri 3 Mandau": 32,
    "SMAN 4 MEDAN": 33,
    "SMA Negeri 1 Tarutung": 34,
    "SMA Negeri 1 Binjai": 35,
    "SMA Negeri 1 Pematang Siantar": 36,
    "SMA Sutomo 2 Medan": 37,
    "SMA Negri 1 Sidamanik": 38,
    "SMK Negeri 1 Lubuk Pakam": 39,
    "SMA Negeri 2 Tarutung": 40,
    "SMA Katolik Tri Sakti Medan": 41,
    "SMA Negeri 1 Simanindo": 42,
    "SMA Negeri 1 Sipoholon": 43,
    "SMA Negeri 1 Laguboti": 44,
    "SMA Negeri 2 Soposurung Balige": 45,
    "SMA N 4 BINJAI": 46,
    "SMA Negeri 12 Medan": 47,
    "SMA Swasta Katolik Budi Murni 1 Medan": 48,
    "SMA Negeri 2 Rantau Utara": 49,
    "SMA As-syafi'iyah Medan": 50,
    "SMA NEGERI 2 BINJAI": 51,
    "SMK Telkom Sandhy Putra Jakarta": 52,
    "SMA Swasta Bintang Timur Balige ": 53,
    "SMAN 1 Pahae Julu": 54,
    "SMA Negeri 2 Pematang Siantar": 55,
    "SMA Negeri 1 Tarutung  ": 56,
    "SMA Methodist 2 Medan": 57,
    "SMA Negeri 1 Pandan": 58,
    "SMA Negeri 8 Medan": 59,
    "SMA Sultan Agung Pematang Siantar": 60,
    "SMA Sutomo 1 Medan": 61,
    "SMA Negeri 1 Siborongborong": 62,
    "SMA St Thomas 1 Medan": 63,
    "SMA Negeri 3 Pematang Siantar": 64,
    "SMA NEGERI 1 KUALA TUNGKAL": 65,
    "SMA Negeri 1 Siantar Narumonda ": 66,
    "SMA Rk Bintang Timur Pematangsiantar": 67,
    "SMA Negeri 2 Siborongborong": 68,
    "SMA SANTO THOMAS 2 MEDAN": 69,
    "SMA Santa Maria Medan": 70,
    "SMA Katolik Mariana Medan": 71,
    "SMA Negeri 1 Pangururan": 72,
    "SMA Negeri 1 Sumbul": 73,
    "SMA Katolik Xaverius Padang": 74,
    "SMA SWASTA DHARMA BAKTI LUBUK PAKAM": 75,
    "SMA Negeri 15 Medan": 76,
    "Smk Telkom Sandhy Putra Medan": 77,
    "SMA Budi Murni 2 Medan": 78,
    "SMA SANTA LUSIA": 79,
    "SMA Negeri 1 Siantar Narumonda": 80,
    "SMK Negeri 1 Balige": 81,
    "SMK RK Budi Mulia Pematang Siantar": 82,
    "SMA Negeri 1 Plus Matauli Pandan Sibolga": 83,
    "SMAN 4 BINJAI": 84,
    "SMA Negeri 1 Bandar": 85,
    "SMA Methodist 1 Medan": 86,
    "SMA Katolik Sibolga": 87,
    "SMA St Thomas 2 Medan": 88,
    "SMA Negeri 1 Sibolga": 89,
    "SMA SWASTA IR.H.DJUANDA": 90,
    "SMA NEGERI 2 TEBING TINGGI": 91,
    "SMA Negeri 1 Silaen": 92,
    "SMK Negeri 2 Pakkat": 93,
    "SMA NEGERI 5 MEDAN": 94,
    "SMAN 1 LUMBAN JULU": 95,
    "SMA Swasta Assisi Siantar": 96,
    "SMK telkom sandhy putra medan": 97,
    "SMA Swasta Pelita Pematang Siantar": 98,
    "SMA N 1 Sidikalang": 99,
    "undefined": 100,
    "SMA Tri Ratna Sibolga": 101,
    "SMA Gajah Mada Medan": 102,
    "Methodist 5 Medan": 103,
    "SMK Telkom Sandhy Putra Medan": 104,
    "SMAN 75 JAKARTA": 105,
    "SMA Negeri 1 Kisaran": 106,
    "SMA Negeri 11 Medan": 107,
    "SMA Negeri 1 Lumban Julu": 108,
    "SMA Negeri Laguboti": 109,
    "SMA Negeri 1 Kualah Hulu": 110,
    "SMA Katolik Cinta Kasih Tebing Tinggi": 111,
    "SMA Kristen Kalam Kudus Pematang Siantar": 112,
    "SMA Negeri 31 Jakarta": 113,
    "SMA Negeri 1 Lubuk Pakam": 114,
    "SMA Negeri 2 Bandar": 115,
    "SMA NEGERI 3 BANDUNG": 116,
    "SMA NEGERI 2 BALIGE": 117,
    "SMA Negeri 6 Medan": 118,
    "SMA Negeri 2": 119,
    "SMK RK Bintang Timur Pematang Siantar": 120,
    "SMA Negeri 4 Pematangsiantar": 121,
    "SMA Negeri 1 Uluan": 122,
    "SMA WAGE RUDOLF SUPRATMAN 2 MEDAN": 123,
    "SMA Negeri 3 Tarutung": 124,
    "SMA Negeri 1 Tebing Tinggi": 125,
    "SMA Unggul Del": 126,
    "SMA BUDI MULIA PEMATANGSIANTAR": 127,
    "SMA NEGERI 2 LINTONGNIHUTA": 128,
    "SMA Unggul Del Laguboti": 129,
    "nan": 130,
    "Sma Negeri 1 Bandar": 131,
    "SMA Negeri 2 Kisaran": 132,
    "SMA Kristen Immanuel Medan": 133,
    "SMA St Thomas 3 Medan": 134,
    "SMA NEGERI 5 KOTA TANGERANG": 135,
    "SMA Mahanaim": 136,
    "SMA Negeri 18 Medan": 137,
    "SMA N 1 Tualang": 138,
    "SMA Negeri 4 Takengon": 139,
    "SMA SWASTA METHODIST 2-KISARAN": 140,
    "SMA Negeri 1 Medan": 141,
    "SMA Negeri 3 Medan": 142,
    "SMA Swasta Methodist Pancurbatu": 143,
    "SMK Cinta Rakyat Pematang Siantar": 144,
    "SMA Santo Thomas 3 Medan": 145,
    "SMA ST YOSEP ": 146,
    "SMK GRAFIKA BINA MEDIA MEDAN ": 147,
    "SMA NEGERI 1 KAB.TANGGERANG": 148,
    "SMA Negeri 4 Mandau": 149,
    "SMA Negeri 7 Medan": 150,
    "SMA Negeri 2 Lubuk Pakam": 151,
    "SMA Negeri 1 Pematangsiantar": 152,
    "SMA NEGERI 1 AIR JOMAN": 153,
    "SMA N 1 PAKKAT": 154,
    "SMK Swasta HKBP STM Pematangsiantar": 155,
    "SMK Negeri 3 Medan": 156,
    "SMA Negeri 2 Bekasi": 157,
    "SMA N 1 Lumbanjulu": 158,
    "SMA N 1 Kualuh Hulu": 159,
    "SMA NEGERI 1 PERBAUNGAN": 160,
    "SMA SWASTA BRIGJEND KATAMSO 1": 161,
    "SMA Swasta Dharma Loka": 162,
    "SMAN 21 JAKARTA": 163,
    "SMK St. Nahanson Parapat": 164,
    "SMA Negeri 1 Lintongnihuta": 165,
    "SMK SWASTA ABDI SEJATI": 166,
    "SMA Negeri 1 Parlilitan": 167,
    "SMA Negeri 1 Pematang Raya Pematang Siantar": 168,
    "SMA Negeri 10 Medan": 169,
    "SMA Methodist 4 Talang Kelapa": 170,
    "SMA Negeri 65 Jakarta": 171,
    "SMA Negeri 2 Medan": 172,
    "SMA Negeri 2 Doloksanggul": 173,
    "SMA Negeri 2 Sibolga": 174,
    "SMA NEGERI 1 TANJUNGBALAI": 175,
    "SMK Negeri 2 Dolok Sanggul": 176,
    "SMA Teladan Pematang Siantar": 177,
    "SMAK St Thomas Rasul Samosir": 178,
    "SMA Negeri 1 Panyabungan Utara ": 179,
    "SMA Negeri 13 Bekasi": 180,
    "SMA Negeri 2 Padang Sidempuan": 181,
    "SMA Methodist Lubuk Pakam": 182,
    "SMA Negeri 1 Raya": 183,
    "SMA Negeri 9 Jakarta": 184,
    "SMA Methodist 12 Medan": 185,
    "SMA NEGERI 8 PEKANBARU": 186,
    "SMAN 9 Pekanbaru": 187,
    "SMK Farmasi Arjuna Laguboti": 188,
    "SMAN 16 Batam": 189,
    "SMA Negeri 1 Sianjur Mulamula": 190,
    "SMA Raksana Medan": 191,
    "SMA Budi Murni 3 Medan": 192,
    "SMA Kristen Kalam Kudus Medan": 193,
    "SMA Negeri 1 Pollung": 194,
    "PERGURUAN KRISTEN METHODIST RANTAUPRAPAT": 195,
    "SMA Negeri 1 Sorkam Barat": 196,
    "SMA RK BINTANG TIMUR RANTAU PRAPAT": 197,
    "SMA YAPIM Medan": 198,
    "SMAS Semen Gresik": 199,
    "SMA Negeri 3 Sibolga": 200,
    "SMA Negeri 1 Kualuh Hulu": 201,
    "SMA Negeri 1 Matauli Pandan": 202,
    "Sma Negeri 5 Pematangsiantar": 203,
    "SMA Negeri 4 Padang Sidempuan": 204,
    "SMA NEGERI 2 KABANJAHE": 205,
    "SMA HKBP 1 Tarutung": 206,
    "SMA SWASTA ASSISI": 207,
    "SMAN 15 BEKASI": 208,
    "SMK NEGERI 9 MEDAN": 209,
    "SMA Negeri 1 Stabat": 210,
    "SMA Negeri 13 Medan": 211,
    "SMA Swasta Santo Thomas 3 Medan": 212,
    "SMA Swasta Yayasan Pendidikan Pancasila": 213,
    "SMAN Madani Palu": 214,
    "SMA Negeri 5 Batam": 215,
    "SMA Santa Maria Pekanbaru": 216,
    "SMA Yadika 8 Bekasi": 217,
    "SMAN 4 Tebing Tinggi": 218,
    "SMA ST YOSEPH MEDAN": 219,
    "SMA Negeri 10 Depok": 220,
    "SMA Negeri 42 Jakarta": 221,
    "SMAK 7 BPK Penabur": 222,
    "SMA Negeri 1 Batam": 223,
    "SMA Negeri 5 Binjai": 224,
    "SMA Negeri 21 Medan": 225,
    "SMKS 3 Parbina Nusantara": 226,
    "SMA Negeri 2 Tanjungbalai": 227,
    "SMA Swasta Dharma Patra Pangkalan Berandan": 228,
    "SMAN 1 DOLOK PANRIBUAN": 229,
    "SMA Methodist 3 Medan": 230,
    "SMA Negeri 53 Jakarta": 231,
    "SMA Negeri 3 Rantau Utara": 232,
    "SMA Telkom Bandung": 233,
    "SMA Negeri 1 Muara": 234,
    "SMA N 2 Semarang": 235,
    "SMAN 1 RANTAU SELATAN": 236,
    "SMK Negeri 1 Kota Bekasi": 237,
    "SMA Negeri 1 Kabanjahe": 238,
    "SMA Negeri 1 Parmaksian": 239,
    "SMA Negeri 3 Banjarbaru": 240,
    "SMAN 1 Gunungsindur": 241,
    "SMA Negeri 6 Jambi": 242,
    "SMA Negeri 1 Baktiraja": 243,
    "SMA Negeri 6 Binjai": 244,
    "SMA Negeri 2 Plus Sipirok": 245,
    "SMA Negeri 11 Pekanbaru": 246,
    "SMA Kristen Yahya ": 247,
}